-- Generated for Oracle Data Modeler
-- Representing the OnTheFly Trip Schema

CREATE TABLE trips (
    id           NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title        VARCHAR2(255) NOT NULL,
    description  VARCHAR2(1000),
    img_url      VARCHAR2(500),
    num_days     NUMBER,
    start_date   DATE,
    end_date     DATE,
    total_cost   NUMBER(10, 2)
);

CREATE TABLE activities (
    id        NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    trip_id   NUMBER NOT NULL,
    activity  VARCHAR2(255) NOT NULL,
    num_votes NUMBER DEFAULT 0,
    CONSTRAINT fk_trip_activities FOREIGN KEY (trip_id)
        REFERENCES trips (id) ON DELETE CASCADE
);

CREATE TABLE destinations (
    id           NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    destination  VARCHAR2(255) NOT NULL,
    description  VARCHAR2(1000),
    city         VARCHAR2(100),
    country      VARCHAR2(100),
    img_url      VARCHAR2(500),
    flag_img_url VARCHAR2(500)
);

CREATE TABLE trips_destinations (
    trip_id        NUMBER NOT NULL,
    destination_id NUMBER NOT NULL,
    PRIMARY KEY (trip_id, destination_id),
    CONSTRAINT fk_td_trip FOREIGN KEY (trip_id)
        REFERENCES trips (id) ON DELETE CASCADE,
    CONSTRAINT fk_td_dest FOREIGN KEY (destination_id)
        REFERENCES destinations (id) ON DELETE CASCADE
);

CREATE TABLE users_trips (
    id       NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    trip_id  NUMBER NOT NULL,
    username VARCHAR2(100) NOT NULL,
    CONSTRAINT fk_ut_trip FOREIGN KEY (trip_id)
        REFERENCES trips (id) ON DELETE CASCADE
);
